---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: singleuserinstances.cnag.eu # ephemeralvolumeclaims.kopf.dev
spec:
  scope: Namespaced
  group: cnag.eu # kopf.dev
  names:
    kind: SingleUserInstance
    plural: singleuserinstances
    singular: singleuserinstance
    shortNames:
      - suis
      - sui
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required: ['lifespan', 'deployment', 'service', 'ingress']
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                lifespan:
                  type: integer
                deployment:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-embedded-resource: true
                service:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-embedded-resource: true
                ingress:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                  x-kubernetes-embedded-resource: true
            status:
              type: object
              x-kubernetes-preserve-unknown-fields: true
      additionalPrinterColumns:
        - name: Lifespan
          type: integer
          priority: 0
          jsonPath: .spec.lifespan
          description: Deployment lifespan.
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp

# ---
# apiVersion: apiextensions.k8s.io/v1
# kind: CustomResourceDefinition
# metadata:
#   name: singleuserinstances.cnag.eu # ephemeralvolumeclaims.kopf.dev
# spec:
#   scope: Namespaced
#   group: cnag.eu # kopf.dev
#   names:
#     kind: SingleUserInstance
#     plural: singleuserinstances
#     singular: singleuserinstance
#     shortNames:
#       - suis
#       - sui
#   versions:
#     - name: v1
#       served: true
#       storage: true
#       schema:
#         openAPIV3Schema:
#           type: object
#           properties:
#             spec:
#               required: ['lifespan']
#               type: object
#               x-kubernetes-preserve-unknown-fields: true
#               properties:
#                 lifespan:
#                   type: integer
#             status:
#               type: object
#               x-kubernetes-preserve-unknown-fields: true
#       additionalPrinterColumns:
#         - name: Lifespan
#           type: integer
#           priority: 0
#           jsonPath: .spec.lifespan
#           description: Deployment lifespan.
#         - name: Age
#           type: date
#           jsonPath: .metadata.creationTimestamp
