apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-secret
  namespace: cellxgene
type: opaque
data:
  # Secrets encoded in base64 e.g. `echo -n 'data' | base64`
  AWS_ENDPOINT_URL: 
  AWS_ACCESS_KEY_ID: 
  AWS_SECRET_ACCESS_KEY: 