apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-secret
  namespace: cellxgene
type: opaque
data:
  # Secrets encoded in base64 e.g. `echo -n 'data' | base64`
  AWS_ENDPOINT_URL: aHR0cDovLzEwLjEwLjAuNDo5MDAwLw== # s3bucket.local
  AWS_ACCESS_KEY_ID: YWRtaW4= # admin
  AWS_SECRET_ACCESS_KEY: MTIzNDU2Nzg= # 12345678
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-cred-secret
  namespace: testing
type: opaque
data:
  AWS_ENDPOINT_URL: aHR0cDovLzEwLjEwLjAuNDo5MDAwLw== # s3bucket.local
  AWS_ACCESS_KEY_ID: YWRtaW4= # admin
  AWS_SECRET_ACCESS_KEY: MTIzNDU2Nzg= # 12345678
