apiVersion: v1
kind: ServiceAccount
metadata:
  name: sui-operator
  namespace: cellxgene

---
apiVersion: v1
kind: Secret
metadata:
  name: sui-operator-token
  namespace: cellxgene
  annotations:
    kubernetes.io/service-account.name: sui-operator
type: kubernetes.io/service-account-token

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sui-operator_admin
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["services", "events"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["create"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]
- apiGroups: ["cnag.eu"]
  resources: ["singleuserinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sui-operator_admin
subjects:
- kind: ServiceAccount
  name: sui-operator
  namespace: cellxgene
roleRef:
  kind: ClusterRole
  name: sui-operator_admin
  apiGroup: rbac.authorization.k8s.io