apiVersion: v1
kind: ServiceAccount
metadata:
  name: omicsdm

---
apiVersion: v1
kind: Secret
metadata:
  name: omicsdm-token
  annotations:
    kubernetes.io/service-account.name: omicsdm
type: kubernetes.io/service-account-token

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omicsdm_admin-pods
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "pods/exec", "services", "services/status", "events"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["cnag.eu"]
  resources: ["singleuserinstances"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omicsdm_admin-pods
subjects:
- kind: ServiceAccount
  name: omicsdm
  namespace: default
roleRef:
  kind: ClusterRole
  name: omicsdm_admin-pods
  apiGroup: rbac.authorization.k8s.io