apiVersion: v1
kind: ServiceAccount
metadata:
  name: omicsdm

---
apiVersion: v1
kind: Secret
metadata:
  name: omicsdm-token
  annotations:
    kubernetes.io/service-account.name: omicsdm
type: kubernetes.io/service-account-token

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omicsdm_admin-suis
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments", "deployments/status"]
  verbs: ["get", "list", "create"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["list", "watch"]
- apiGroups: ["cnag.eu"]
  resources: ["singleuserinstances"]
  verbs: ["get", "list", "create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: omicsdm_admin-suis
subjects:
- kind: ServiceAccount
  name: omicsdm
  namespace: default
roleRef:
  kind: ClusterRole
  name: omicsdm_admin-suis
  apiGroup: rbac.authorization.k8s.io