apiVersion: v1
kind: Pod
metadata:
  name: dns-lookup-test
spec:
  containers:
    - name: dns-lookup
      image: busybox
      command:
        - sleep
        - "3600"
      resources:
        limits:
          memory: "256Mi"
          cpu: "500m"
