apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: default
data:
  # /root/.docker/config.json base64 encoded
  .dockerconfigjson: DOCKER_CONFIG_JSON
type: kubernetes.io/dockerconfigjson
